# --- POST-RUN DASHBOARD ---
if st.session_state.swarm_ran and backend_connected:
    
    if not st.session_state.final_results:
        # Pass the raw payload to the backend
        live_incident = {
            "observables": [{"value": s_data["ip"], "type": "ip"}],
            "logs": s_data["logs"]
        }
        orchestrator = SOCAgentOrchestrator(case_id="SOC-LIVE-001", analyst="Autonomous Swarm")
        
        with st.spinner("Swarm executing..."):
            ui_orchestrator.markdown(render_agent_card("Master Orchestrator", "🧠", "routing", is_master=True), unsafe_allow_html=True)
            
            # Run the real orchestrator logic
            st.session_state.final_results = orchestrator.run_incident(live_incident)
            
            st.rerun()

    if st.session_state.final_results:
        ui_orchestrator.markdown(render_agent_card("Master Orchestrator", "🧠", "done", is_master=True), unsafe_allow_html=True)
        st.divider()

        # PULL REAL DATA GENERATED BY THE LLM
        agg_data = st.session_state.final_results.get("aggregated_data", {})
        real_mitre = agg_data.get("mitre", ["T1078 - Valid Accounts (Fallback)"])
        real_tools = agg_data.get("tools", ["SIEM API (Fallback)"])
        real_actions = agg_data.get("actions", ["Isolate Host"])

        st.markdown("### 🛠️ Agent Tactics & Tool Orchestration")
        mitre_html = " ".join([f"<span class='mitre-tag'>{m}</span>" for m in real_mitre])
        tool_html = " ".join([f"<span class='tool-tag'>{t}</span>" for t in real_tools])
        st.markdown(f"**AI-Determined MITRE Mapping:** {mitre_html}", unsafe_allow_html=True)
        st.markdown(f"**Autonomously Queried Tools:** {tool_html}", unsafe_allow_html=True)
        st.write("")

        col1, col2 = st.columns([1.5, 1])
        
        with col1:
            st.markdown("### 🛑 Live Containment Playbook")
            
            if exec_mode == "Human-in-the-Loop" and not st.session_state.human_approved:
                st.warning("⚠️ **HUMAN OVERRIDE REQUIRED:** Swarm consensus reached. Awaiting approval to execute containment playbook.")
                if st.button("✅ Approve AI Playbook", type="secondary"):
                    st.session_state.human_approved = True
                    st.rerun()
            else:
                action_html = "<br>".join([f"> Executing: {act}... <span class='success-text'>SUCCESS</span>" for act in real_actions])
                
                st.markdown(f"""
                <div class="action-log">
                    [ORCHESTRATOR] Semantic Memory updated. Real-time consensus reached.<br>
                    <br>
                    {action_html}<br>
                    <br>
                    [STATUS] <span class="success-text">ENVIRONMENT SECURED.</span>
                </div>
                """, unsafe_allow_html=True)

        with col2:
            st.markdown("### 🧠 Raw Explainability Data")
            st.json(st.session_state.final_results.get("specialists", {}))
