import React from 'react';
import { X, Printer, Download, ShieldCheck, AlertTriangle, FileText, Check } from 'lucide-react';

export default function ExecutiveReportModal({ isOpen, onClose, activeScenario, logs, finalReport }) {
  if (!isOpen) return null;

  const alert = activeScenario.initialAlert;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-[#0f172a] border border-cyan-500/30 rounded-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto shadow-2xl flex flex-col">
        
        {/* Modal Header */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between sticky top-0 bg-[#0f172a] z-10 no-print">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <h2 className="text-sm font-bold text-slate-100 uppercase tracking-wide">
              Executive Cyber Incident & Root Cause Report
            </h2>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-black font-bold text-xs font-mono flex items-center gap-1.5 transition-all shadow-md shadow-cyan-500/20"
            >
              <Printer className="w-3.5 h-3.5" /> Print / Export PDF
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-all"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Report Content Body */}
        <div className="p-6 flex flex-col gap-6 text-slate-200 text-xs font-sans print:p-0">
          
          {/* Report Header Card */}
          <div className="border-b border-slate-700 pb-4 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <div className="text-xs font-mono text-cyan-400 font-bold">CONFIDENTIAL // SOC INCIDENT AUDIT</div>
              <h1 className="text-xl font-extrabold text-slate-100 mt-1">{activeScenario.title}</h1>
              <p className="text-xs text-slate-400 mt-0.5">Generated by AEGIS-SOC Multi-Agent Autonomous Platform</p>
            </div>
            <div className="font-mono text-right text-xs">
              <div>Incident ID: <strong className="text-cyan-300">{alert.alertId}</strong></div>
              <div>Severity: <strong className="text-rose-400 uppercase">{activeScenario.severity}</strong></div>
              <div>Timestamp: <span className="text-slate-400">{alert.timestamp}</span></div>
            </div>
          </div>

          {/* Incident Summary & Risk Matrix */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 font-mono">
            <div className="bg-slate-900/90 p-3 rounded-xl border border-slate-800">
              <div className="text-[10px] text-slate-400">AUTONOMOUS CONFIDENCE</div>
              <div className="text-lg font-bold text-emerald-400">98.4%</div>
            </div>
            <div className="bg-slate-900/90 p-3 rounded-xl border border-slate-800">
              <div className="text-[10px] text-slate-400">ESTIMATED MITIGATION TIME</div>
              <div className="text-lg font-bold text-cyan-400">1.4 Seconds</div>
            </div>
            <div className="bg-slate-900/90 p-3 rounded-xl border border-slate-800">
              <div className="text-[10px] text-slate-400">REGULATORY RISK</div>
              <div className="text-lg font-bold text-amber-400">GDPR & PCI-DSS</div>
            </div>
          </div>

          {/* Root Cause Analysis */}
          <div className="bg-slate-900/70 p-4 rounded-xl border border-slate-800">
            <h3 className="font-bold text-xs text-cyan-300 uppercase font-mono mb-2">Executive Root Cause Summary</h3>
            <p className="text-slate-300 leading-relaxed">
              {activeScenario.summary} Compromise originated at workstation <strong className="text-slate-100">{alert.host}</strong> via stolen session token by user <strong className="text-slate-100">{alert.user}</strong> from adversary IP <strong className="text-slate-100">{alert.srcIp}</strong>. Encrypted C2 exfiltration attempt intercepted and blocked by autonomous multi-agent containment workflow.
            </p>
          </div>

          {/* MITRE ATT&CK Mapping Table */}
          <div>
            <h3 className="font-bold text-xs text-cyan-300 uppercase font-mono mb-2">MITRE ATT&CK Framework Mapping</h3>
            <div className="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">
              <table className="w-full text-left font-mono text-xs">
                <thead className="bg-slate-950 text-slate-400 border-b border-slate-800">
                  <tr>
                    <th className="p-2.5">Technique ID</th>
                    <th className="p-2.5">Category</th>
                    <th className="p-2.5">Threat Verdict</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800 text-slate-300">
                  {activeScenario.mitreTechniques.map(tech => (
                    <tr key={tech}>
                      <td className="p-2.5 font-bold text-rose-400">{tech}</td>
                      <td className="p-2.5 text-slate-400">{activeScenario.category}</td>
                      <td className="p-2.5 text-emerald-400 font-bold">DETECTED & MITIGATED</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Autonomous Containment Audit */}
          <div>
            <h3 className="font-bold text-xs text-cyan-300 uppercase font-mono mb-2">Containment Audit Record</h3>
            <div className="flex flex-col gap-2 font-mono">
              {activeScenario.recommendedActions.map(action => (
                <div key={action.actionId} className="bg-slate-900/90 p-2.5 rounded-lg border border-slate-800 flex items-center justify-between text-xs">
                  <div>
                    <span className="font-bold text-slate-100">{action.type}</span>
                    <span className="text-slate-400 ml-2">({action.target})</span>
                  </div>
                  <span className="text-emerald-400 font-bold flex items-center gap-1">
                    <Check className="w-3.5 h-3.5" /> EXECUTED
                  </span>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
